better way of running the bluebomb helper script.
hacks-guide/Guide_Wii pull request #115
Opened 2024-09-16 17:04 UTC by sctech-tr

**Description**

this pr basically fits the entire downloading and running process into one command, so the users don't have to run 3 commands.

the old commands are:
```bash
wget https://wii.hacks.guide/assets/files/bluebomb-helper.sh
chmod +x bluebomb-helper.sh
./bluebomb-helper.sh
```
and the new command is:
```bash
wget -qO- https://wii.hacks.guide/assets/files/bluebomb-helper.sh | sh
```

if i did anything wrong, please notify me because this is my first time contributing here.

2024-09-16 17:36 UTC, Naim2000 requested changes

2024-09-16 17:36 UTC, Naim2000 commented on _pages/en_US/bluebomb.md
> +   wget -qO- https://wii.hacks.guide/assets/files/bluebomb-helper.sh | sh
```suggestion
   wget -qO- https://wii.hacks.guide/assets/files/bluebomb-helper.sh | bash
```
![image](https://github.com/user-attachments/assets/b3f10a4d-e0f1-4939-b48e-c3442522c146)

2024-09-16 18:31 UTC, sctech-tr commented
i did it
i have no idea why sh fails, it's just a symlink to bash

2024-09-16 18:41 UTC, danny8376 commented
> i did it i have no idea why sh fails, it's just a symlink to bash (it may be different in other systems, so nice idea)

not always, like debian/ubuntu use dash, not bash for sh, you should never expect sh to work like bash in any case

2024-09-17 04:27 UTC, sctech-tr commented
how about the $SHELL variable?

2024-09-17 04:28 UTC, sctech-tr reviewed
nice

2024-09-17 04:30 UTC, sctech-tr commented
it even works on iSH shell
![image](https://github.com/user-attachments/assets/5f95312f-c461-405e-b611-39acebd6f775)

2024-09-17 08:39 UTC, danny8376 commented
> it even works on iSH shell
The script is just written with bash in mind
so... just make it run with bash
if they don't have bash and still want to run it, they need to figure it out
getting weird error cuz the user using weird shell is the least you want

2024-09-17 15:48 UTC, sctech-tr commented
![image](https://github.com/user-attachments/assets/f2db81e9-cb5e-4b05-9515-011439d04600)
%96 of the people who want to homebrew their wii use windows, they are not going to be linux masters. only the remaining %4 of the people can probably figure out how to run it in bash

2024-09-17 16:06 UTC, danny8376 commented
figure what? bash is literally in most distro, you literally just need to type bash, like what originally was
if they don't have bash, they most likely using niche distro which they probably know what's going 
if they're not using bash as their main shell, yes, they likely know how to fix it
but you just make what originally will globally works into something that need extra work, no benefit
it absolutely make no sense when you literally need bash to run, then rely on something like $SHELL to introduce uncertainty

2024-09-17 16:44 UTC, sctech-tr commented
ok use bash
![image](https://github.com/user-attachments/assets/5ed81e0c-9fb8-48b5-bad5-452aa8ae1e70)

2024-10-13 14:14 UTC, sctech-tr commented
> niche distro
you don't automatically be a *niche* distro by just not using bash by default. so, by this logic, arch is a niche distro as well.

2025-03-29 17:15 UTC, playerjmr commented
closing this and marking it as not planned. if it aint broke dont fix it.

2025-03-29 17:15 UTC, closed without merging