Update and rename usb-loaders.md to wii-loaders.md
hacks-guide/Guide_Wii pull request #22
Opened 2023-10-06 04:48 UTC by playerjmr

complete overhaul of this page with updated terminology, features, and fixed various other mistakes.

**Description**

2023-10-06 05:08 UTC, emilydaemon requested changes

2023-10-06 05:08 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> +The official Wii menu forwarder installer for Wiiflow Lite can be found on the [Open Shop Channel](https://oscwii.org/library/app/wiiflow_channel_installer). Run the app in the Homebrew Channel to in
typo: "fowader"

2023-10-06 05:08 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> +    + SD cards are fully supported for loading Wii games
typo(?): ful stop missing

2023-10-06 05:08 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> ++ If USB Loader GX says "Waiting for HDD..." with a 20 second countdown, it is very likely that it cannot detect your USB device. Try to exit out of the app, ensure your USB device is plugged into th
"bottom port" may cause confusion for those who have their Wiis in a vertical orientation. perhaps "port closest to the edge" would be best

2023-10-06 05:08 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> ++ Using a USB dongle in Rock Band.
proposed change: add `+ Running Call of Duty.`

2023-10-06 06:07 UTC, playerjmr commented on _pages/en_US /wii-loaders.md
> ++ Using a USB dongle in Rock Band.
Which call of duty? There are like five of them. Did you mean black ops?

2023-10-06 06:44 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> ++ Using a USB dongle in Rock Band.
I think all of them need to be run under a different cIOS

2023-10-06 22:37 UTC, playerjmr commented on _pages/en_US/wii-loaders.md
> +The official Wii menu forwarder installer for Wiiflow Lite can be found on the [Open Shop Channel](https://oscwii.org/library/app/wiiflow_channel_installer). Run the app in the Homebrew Channel to in
```suggestion
The official Wii menu forwarder installer for Wiiflow Lite can be found on the [Open Shop Channel](https://oscwii.org/library/app/wiiflow_channel_installer). Run the app in the Homebrew Channel to install the forwarder. The USB Loader GX official forwarder can be found on the [SourceForge](https://sourceforge.net/projects/usbloadergx/files/Releases/Forwarders/USB%20Loader%20GX-UNEO_Forwarder_5_1_AHBPROT.wad/download) page. You can install it with [YAWM ModMii Edition](yawmme).
```

2023-10-06 22:38 UTC, playerjmr commented on _pages/en_US/wii-loaders.md
> +    + SD cards are fully supported for loading Wii games
```suggestion
    + SD cards are fully supported for loading Wii games.
```

2023-10-06 22:42 UTC, playerjmr commented on _pages/en_US/wii-loaders.md
> ++ If USB Loader GX says "Waiting for HDD..." with a 20 second countdown, it is very likely that it cannot detect your USB device. Try to exit out of the app, ensure your USB device is plugged into th
```suggestion
+ If USB Loader GX says "Waiting for HDD..." with a 20 second countdown, it is very likely that it cannot detect your USB device. Try to exit out of the app, ensure your USB device is plugged into the bottom port if Wii is placed horizontally, or the port closest to the edge when the Wii is placed vertically. It may also be formatted incorrectly. Ensure that your USB drive is formatted to FAT32, with the MBR partition table, and 32kb (32768 bytes) allocation unit size/cluster size.
```

2023-10-06 22:44 UTC, playerjmr commented on _pages/en_US /wii-loaders.md
> ++ Using a USB dongle in Rock Band.
it just seems unclear to just say "call of duty". honestly three examples is probably enough anyway

2023-10-07 09:58 UTC, emilydaemon commented on _pages/en_US /wii-loaders.md
> ++ Using a USB dongle in Rock Band.
ah, I see.

2023-10-07 09:59 UTC, emilydaemon approved these changes

2023-10-08 04:09 UTC, lifehackerhansol approved these changes

2023-10-08 04:09 UTC, merged